project/src/main/webapp/index.html
project/src/main/webapp/style.css

Added HTML and CSS to main page.

Add HTML/CSS for main page

---

project/src/main/webapp/index.html
project/src/main/webapp/style.css

Add trend frequency in written text.

Add trend frequency section

---

project/src/main/webapp/index.html
project/src/main/webapp/script.js
project/src/main/webapp/style.css

Add carousel of trending topic titles

---

project/src/main/webapp/index.html
project/src/main/webapp/script.js
project/src/main/webapp/style.css

Add dots that change the trending topic when clicked.

Trending topic dots

---

project/src/main/webapp/index.html
project/src/main/webapp/style.css

Create placeholder cards for articles.

Create placeholder cards for articles

---

project/src/main/webapp/index.html
project/src/main/webapp/script.js
project/src/main/webapp/style.css

Add main page mobile design

---

project/src/main/webapp/index.html
project/src/main/webapp/script.js
project/src/main/webapp/style.css

Add main page design for tablet.

Add main page tablet design

---

project/src/main/webapp/index.html
project/src/main/webapp/script.js
project/src/main/webapp/style.css

Trend frequency mobile and tablet design (click on image to better see mobile/tablet layout).

Add trend frequency mobile and tablet design

---

project/pom.xml
project/src/main/java/com/google/sps/servlets/Article.java
project/src/main/java/com/google/sps/servlets/DataServlet.java
project/src/main/java/com/google/sps/servlets/NewsService.java
project/src/main/java/com/google/sps/servlets/Topic.java

Recreated the PR because there were issues with the last one that prevented me from being able to merge the changes.

RSS Feed XML Parsing setup

---

project/src/main/webapp/index.html
project/src/main/webapp/style.css

Add mobile and tablet design for trending topic section.

Add mobile and tablet design for trending topic section

---

project/src/main/webapp/index.html

Initial merge conflict mistake correction.

Fix merge mistake

---

project/src/main/webapp/index.html
project/src/main/webapp/script.js
project/src/main/webapp/style.css

Auto-generate articles. Lagging fixed. Extended preloader time to account for time to fetch articles.

Auto-generate articles

---

project/src/main/webapp/index.html
project/src/main/webapp/script.js
project/src/main/webapp/style.css

Change trend retrieval to make it not hard coded.

Update trend retrieval

---

project/src/main/webapp/index.html
project/src/main/webapp/script.js
project/src/main/webapp/style.css

First attempt at bubble graph

---

.github/workflows/maven-feature.yml
project/src/main/java/com/google/sps/servlets/Article.java
project/src/main/java/com/google/sps/servlets/NewsService.java

This is just a start to see if the workflows will work properly by just creating a build and testing it.

Added basic workflow for github actions

---

project/src/main/java/com/google/sps/servlets/NewsServlet.java
project/src/main/webapp/index.html
project/src/main/webapp/script.js
project/src/main/webapp/style.css

Stack bubbles

---

project/src/main/webapp/index.html
project/src/main/webapp/script.js
project/src/main/webapp/style.css

Add sentiment colors

---

project/src/main/webapp/index.html
project/src/main/webapp/script.js
project/src/main/webapp/style.css

Translate sentiment key

---

project/src/main/webapp/script.js
project/src/main/webapp/style.css

Update UI on mobile and tablet, which includes sentiment bubbles, sentiment key, and translation.

Update UI on mobile and tablet

---

project/src/main/java/com/google/sps/data/TrendService.java
project/src/test/java/com/google/sps/TrendRSSFeedTest.java

This stores trends from a country (that is not the U.S.) the first time it is accessed.

Cache foreign trends

---

project/src/main/webapp/script.js
project/src/main/webapp/style.css

Update mobile tablet

---

project/src/main/webapp/script.js
project/src/main/webapp/style.css

Updated video card design layout so that really long URLs in descriptions won't overlap with thumbnail images.

Update video card design
